### ISSUE TITLE
Shaders fail to compile with error "ReShade 3.0+ is required to use this header file" when porting my existing library of shaders and textures over

### ISSUE THREAD

**Issue by WingedAsarath** [liuxd17thu/reshade#4]
I tried to move to Aurorashade today from an existing Reshade installation. I have an existing library of presets, shaders, and textures which I left in place (after backing up), however, when I open AuroraShade my shaders fail to compile with the error "ReShade 3.0+ is required to use this header file".

Looking at [this post here on the ReShade forums](https://reshade.me/forum/troubleshooting/2991-solved-reshade-3-0-is-required-to-use-this-header-file), the issue seems to stem from the fact that AuroraShade has its ReShade version set to 0.0.0.0 according to both the log file and in-game overlay.

[I can see that other users reported this in the AuroraShade reddit thread but could not solve it themselves.](https://www.reddit.com/r/ffxiv/comments/1aukdl1/comment/kra9nh5/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

I've attached my log file to this post which shows the versioning issue and the errors displayed.

[ReShade.log](https://github.com/liuxd17thu/reshade/files/14841832/ReShade.log)

**Comment by liuxd17thu** [comment]
It's an issue in the GitHub Actions workflow. I will fix it later.
Here's the binary compiled locally on my PC:
[Aurora-R6.1-d484738.zip](https://github.com/liuxd17thu/reshade/files/14892214/Aurora-R6.1-d484738.zip)
